# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: heitorsa/salesforce-ci:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Authenticates
        run: |
          mkdir -p /tmp/keys
          echo $DEVHUB_SERVER_KEY >/tmp/keys/server64.key
          base64 -d /tmp/keys/server64.key >/tmp/keys/server.key
          cat /tmp/keys/server.key
          sfdx force:auth:jwt:grant --clientid $DEVHUB_CLIENT_ID --jwtkeyfile /tmp/keys/server.key --username heitor.saraujo@gmail.com.dev --instanceurl https://login.salesforce.com -a DEV_HUB
          sfdx force:org:create -f config/project-scratch-def.json -v DEV_HUB -t scratch --setdefaultusername -d 1
          sfdx force:source:push